# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 20, 57, 55, 258966, tzinfo=utc), editable=False, verbose_name='auto_now_add=true'),
        ),
    ]
