# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-02 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0002_auto_20170110_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(default='0.0', max_length=255)),
                ('lon', models.CharField(default='0.0', max_length=255)),
                ('accx', models.CharField(default='0', max_length=255)),
                ('accy', models.CharField(default='0', max_length=255)),
                ('accz', models.CharField(default='0', max_length=255)),
                ('gyrx', models.CharField(default='0', max_length=255)),
                ('gyry', models.CharField(default='0', max_length=255)),
                ('gyrz', models.CharField(default='0', max_length=255)),
                ('magx', models.CharField(default='0', max_length=255)),
                ('magy', models.CharField(default='0', max_length=255)),
                ('magz', models.CharField(default='0', max_length=255)),
                ('est_alt', models.CharField(default='0', max_length=255)),
                ('vario', models.CharField(default='0', max_length=255)),
                ('rc_throttle', models.IntegerField(default=0)),
                ('rc_pitch', models.IntegerField(default=0)),
                ('rc_yaw', models.IntegerField(default=0)),
                ('rc_roll', models.IntegerField(default=0)),
                ('vbat', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 2, 2, 13, 44, 35, 913834, tzinfo=utc), editable=False, verbose_name='auto_now_add=true')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 2, 13, 44, 35, 911522, tzinfo=utc), editable=False, verbose_name='auto_now_add=true'),
        ),
    ]
