# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-02 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0003_auto_20170202_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronedata',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 2, 13, 46, 18, 502500, tzinfo=utc), editable=False, verbose_name='auto_now_add=true'),
        ),
        migrations.AlterField(
            model_name='dronedata',
            name='vbat',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 2, 13, 46, 18, 499683, tzinfo=utc), editable=False, verbose_name='auto_now_add=true'),
        ),
    ]
