# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-06 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0009_auto_20170202_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronedata',
            name='angx',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='dronedata',
            name='angy',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='dronedata',
            name='heading',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='dronedata',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 6, 23, 1, 1, 269768, tzinfo=utc), editable=False, verbose_name='auto_now_add=true'),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 6, 23, 1, 1, 267374, tzinfo=utc), editable=False, verbose_name='auto_now_add=true'),
        ),
    ]
